config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  namespace :backoffice do
    resources :categories, except: [:destroy, :show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    resources :send_mail, only: [:edit, :create]
  end

  namespace :checkout do
    resources :payments , only: [:create]
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :deashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  get 'backoffice', to: 'backoffice/dashboard#index'

  devise_for :admins, :skip => [:registration]
  devise_for :members , controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations' 
  }
  get 'home/index'
  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backoffice/admins_controller.rb
Class Backoffice::AdminsController < BackofficeController
before_action :set_admin, only: [:edit, :update, :destroy]
bafter_action :verify_authorized, only: [:new, :destroy]
bafter_action :verify_policy_scoped, only: :index

def index
  # @admins = Admin.all
  # @admins = Admin.with_full_access
  @admins = policy_scope(Admin)
end

  def new
  	@admin = Admin.new
    authorize @admin
  end

  def create
  	@admin = Admin.new(params_admin)
  	if @admin.save
  		redirect_to backoffice_admins_path, notice: get_message_success
  	else
  		render :new
  	end
  end

  def edit

  end

  def update
  	if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
  		redirect_to backoffice_admins_path, notice: get_message_success
  	else
  		render :edit
  	end
  end

  def destroy
  	admin_email = @admin.email
    authorize @admin
    puts "------------------- APAGOU - modal do confirma não funciona -------------------"
  	# if @admin.destroy
  	# 	redirect_to backoffice_admins_path, notice: "O usuário (#{admin_email}) foi excluído com sucesso!"
  	# else
  	# 	render :index
  	# end
  end

  private

  def get_message_success
  	"O usuário (#{ @admin.email }) foi salvo com sucesso!"
  end

  def set_admin
  	@admin = Admin.find(params[:id])
  end

  def params_admin

    if password_blank? 
      params[:admin] = params[:admin].except(:password, :password_confirmation)
    end

    if @admin.blank?
      params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end

  end

  def password_blank?
    params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
  end

End

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only:[:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: get_message_success
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: get_message_success
    else
      render :edit
    end
  end

  private

  def get_message_success
    "A Categoria ( #{@category.description} ) foi salva com sucessso!"
  end

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:description)
  end

end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)
    
    if @category.valid?
      @category.save!
    end

    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
  def index
    %x(bundle exec erd --filename='public/diagram')
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

	def edit
		@admin = Admin.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	def create
		begin
			AdminMailer.send_mail(current_admin, params[:'recipient-text'], params[:'subject-text'], params[:'message-text']).deliver_now
			@notify_message = t('messages.send_mail_success')
			@notify_tag = "success"
		rescue
			@notify_message = t('messages.send_mail_error')
			@notify_tag = "error"
		end
		respond_to do |format|
			format.js
		end
	end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	layout "backoffice"
	before_action :authenticate_admin!

	def pundit_user
		current_admin
	end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
	OptionsForRules = Struct.new(:id, :description)

	def options_for_rule
		Admin.roles_i18n.map do |key, value|
			OptionsForRules.new(key, value)
		end
	end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render "backoffice/admins/shared/form", title: "Editando Usuário" %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Usuário</h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('messages.listing', model: @admins.model_name.human(count:2)) %>
    <% if policy(@admins).new? %>
      <%= link_to new_backoffice_admin_path, class:"btn btn-success btn-circle pull-right", style:"    margin-top: -5px;" do %>
        <i class="fa fa-plus"></i>
      <% end %>
    <% else %>
        <%= link_to "#", class:"btn btn-success btn-circle pull-right",  disabled: "disabled", style:"margin-top: -5px;" do %>
        <i class="fa fa-plus"></i>
      <% end %>
    <% end %>
  </div>
  <!-- /.panel-heading -->

  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>#</th>
          <th>Nome</th>
          <th>Perfil de acesso</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.id %></td>
              <td><%= admin.name %></td>
              <td><%= admin.role_i18n %></td>
              <td>
                <%= link_to edit_backoffice_send_mail_path(admin), class:"btn btn-info btn-circle", remote: true  do %>
                  <i class="fa fa-envelope"></i>
                <% end %>
                <%= link_to edit_backoffice_admin_path(admin.id), class:"btn btn-primary btn-circle" do %>
                  <i class="fa fa-edit"></i>
                <% end %>
                <% if (current_admin.id != admin.id) && policy(@admins).destroy? %>
                  <%= link_to backoffice_admin_path(admin), class: "btn btn-danger btn-circle", method: :delete,
                    data: {confirm: "Você tem certeza?",
                    text: t('messages.confirm_with',item: admin.name),
                    'confirm-button-text': 'SIM',
                    'cancel-button-text': 'NÃO',
                    'confirm-button-color': '#66CD00',
                    'sweet-alert-type': 'warning',
                    confirmButtonText: 'Yes, delete it!'} do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                <% else %>
                  <%= link_to '#', class: "btn btn-danger btn-circle", disabled: "disabled" do %>
                  <i class="fa fa-trash"></i>
                <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render ('backoffice/admins/shared/send_mail') %>

app/views/backoffice/admins/new.html.erb
<%= render "backoffice/admins/shared/form", title: "Adicionando um novo Usuário" %>