config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  namespace :backoffice do
    resources :categories, except: [:destroy, :show]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    resources :send_mail, only: [:edit, :create]
  end

  namespace :checkout do
    resources :payments , only: [:create]
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :deashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  get 'backoffice', to: 'backoffice/dashboard#index'

  devise_for :admins, :skip => [:registration]
  devise_for :members , controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations' 
  }
  get 'home/index'
  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  # Constant
  QTT_PER_PAGE = 6

  # Ratyrate
  ratyrate_rateable "quality"

  # Callbacks
  before_save :markdown_to_html

  # ENUM
  enum status: [:active, :processing, :sold]

  # Association
  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comment

  # Validation
  validates :title, :category, :finish_date, :picture, :description_markdown, :description_short, presence: true
  validates :price, numericality: { greater_than: 0 }

  # scope
  scope :descending_order, ->(page){
    order(created_at: :asc).page(page).per(QTT_PER_PAGE)
  }
  scope :to_the, ->(member){ where(member: member) }
  scope :by_category, ->(id,page) {
    where(category: id).page(page).per(QTT_PER_PAGE)
  }
  scope :search, -> (term, page) {
    where("title LIKE lower(?)", "%#{term.downcase}%").page(page).per(QTT_PER_PAGE)
  }

  scope :random, -> (quantity) { 
    # Rails.env.production?
    #   limit(quantity).order("RAND()") #MySql
    # else
    limit(quantity).order("RANDOM()") #SQLite
    # end
    # limit(quantity).order("RAND()") #MySql
  }

  #paperclip
  has_attached_file :picture, styles: { large: "900x400#", medium: "320x150#", thumb: "100x100#" },
  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #money ruby
  monetize :price_cents

  def second
    self[1]
  end

  def third
    self[2]
  end

  private

  def markdown_to_html
    options = {
      filter_html: true,
      link_attributes: {
        rel: "nofollow",
        target: "_blank"
      }
    }

    extensions = {
      space_after_headers: true,
      autolink: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    self.description = markdown.render(self.description_markdown).html_safe
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  #Enums
  enum role: [:full_access, :restricted_access]
  #Scoopes
  scope :with_full_access, -> { where(role: 'full_access') }
  scope :with_restricted_access, -> { where(role: 'restricted_access') }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
	include FriendlyId
	friendly_id :description, use: :slugged

	#Associations
	has_many :ads

	#Validations
	validates_presence_of :description

	#scope
	scope :order_by_description, -> { order(description: :asc) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ApplicationRecord
  #Ratyrate gem
  ratyrate_rater

  #Associations
  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member
  #Validations
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private

    def nested_attributes
      if nested_attributes_blank?
        errors.add(:base, "Necessário preencher o Primeiro e o Segundo Nome")
      end
    end

    def nested_attributes_blank?
      profile_member.first_name.blank? || profile_member.second_name.blank?
    end
end

app/models/order.rb
class Order < ApplicationRecord

  enum status: [:requested, :waiting, :analysing, :paid, :avaliable, :dispute, :returned, :canceled, 
    :debited, :temporary_retention]

  #Assossiations
  belongs_to :ad
  belongs_to :buyer, class_name: "Member"
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile_member.rb
class ProfileMember < ApplicationRecord
  belongs_to :member

  def full_name
    "#{self.first_name} #{self.second_name}"
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_member_location, :if => :storable_location?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_device"
    elsif devise_controller? && resource_name == :member
      "site_device"
    else
      "application"
    end
  end

  def user_not_authorized
    flash[:alert] = "Você não tem autorização para executar essa ação."
    redirect_to(request.referrer || root_path)
  end

  private
    def storable_location?
      request.get? && !devise_controller? && !request.xhr?
    end

    def store_member_location
      store_location_for(:member, request.fullpath)
    end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	layout "backoffice"
	before_action :authenticate_admin!

	def pundit_user
		current_admin
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	layout "site"

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_member
  end
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Usuário</h1>
<% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <% @admin.errors.full_messages.each do |message| %>
            <li>
                <%= message %>
            </li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= title %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
        <%= form_for([:backoffice, @admin])  do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class:"form-control", placeholder:"Ex: Nome do usuario" %>
            </div>
            <div class="form-group">
            	<%= f.label :email %>
            	<%= f.text_field :email, class:"form-control", placeholder:"Ex: email@example.com" %>
        	</div>
            <% if policy(@admin).edit? %>
                <div class="form-group">
                    <%= f.collection_radio_buttons(:role, options_for_rule, :id, :description) do |b| %>
                        <div class="radio">
                            <%= b.label { b.radio_button + b.text } %>
                        </div>
                    <% end %>
                </div>
            <% end %>
            <div class="form-group">
              <%= f.label :password %>
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off", class:"form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation %><br />
                <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
            </div>
            <div class="form-group">
            	<%= f.submit "Salvar", class:"btn btn-default" %>
        	</div>
        <% end %>
        </div>
     </div>
</div>

app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %>:</h4>
      </div>
      <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
        <div class="modal-body">
            <div class="form-group">
              <label for="recipient-text" class="control-label"><%= t('labels.recipient') %>:</label>
              <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly")%>
            </div>
            <div class="form-group">
              <label for="subject-text" class="control-label"><%= t('labels.subject') %>:</label>
              <%= text_field_tag(:'subject-text', nil, class: "form-control" , require: "require")%>
            </div>
            <div class="form-group">
              <label for="message-text" class="control-label"><%= t('labels.message') %>:</label>
              <%= text_area_tag(:'message-text', nil, class: 'form-control') %>
            </div>
            </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
          <%= submit_tag t('buttons.send_message'), class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
    <%= javascript_tag "$.notify({ message: '#{notice}' }, { type:'success', placement: {from: 'top', align: 'center'}});" %>
<% end %>

<% if alert %>
    <%= javascript_tag "$.notify({ message: '#{alert}' }, { type:'success' , placement: {from: 'top',align: 'center'}});" %>
<% end %>